### ISSUE TITLE
RendererOptions values override default values in Renderer

### ISSUE THREAD

**Issue by scailbc** [lightning-js/solid#17]
In [core/renderer/index.ts](https://github.com/lightning-js/solid/blob/v0.8.7/src/core/renderer/index.ts) we are defining the default values for the renderer

```js
const defaultOptions: SolidRendererOptions = {
  appWidth: 1920,
  appHeight: 1080,
  deviceLogicalPixelRatio: 0.6666667,
  devicePhysicalPixelRatio: 1,
  rootId: 'app',
  threadXCoreWorkerUrl: undefined,
};
```

These values override the default values defined in the [lightning-js/renderer library](https://github.com/lightning-js/renderer), defined and documented in the file [main-api/RendererMain.ts](https://github.com/lightning-js/renderer/blob/v0.5.0/src/main-api/RendererMain.ts#L257).

This is a bit confusing and from my test the default options defined in the renderer are better, since are based on the device. The defaultOptions here should only have `rootId` and `threadXCoreWorkerUrl`.

Let me know if I'm missing somehting

**Comment by chiefcll** [comment]
0.9.0 is released and default options are removed. rootId still defaults to app

Thanks!
