### ISSUE TITLE
Investigate performance issues on SolidJS & Lightning 3

### ISSUE THREAD

**Issue by wouterlucas** [lightning-js/solid#21]
- Seeing performance issues on 1080p on certain devices with SolidJS Example app
- Getting about ~20 FPS over the expected 45 - 50 FPS

**Comment by chiefcll** [comment]
Looks like linearGradient in the renderer is causing large loss in FPS. Removing that doubles FPS.

**Comment by wouterlucas** [comment]
Is that due to large images being used or does the radial gradient also degrade with smaller (non 1080p full quality) images?

**Comment by chiefcll** [comment]
Lowering the image quality did not make a noticeable change in FPS - I assume this is due to the size of the image (faster download) doesnt affect loading the data on the GPU as its just compression.

**Comment by chiefcll** [comment]
Closing again. We did get significant bump from also setting alpha: 0 on any nodes not in screen.
