### ISSUE TITLE
Rendering html from string

### ISSUE THREAD

**Issue by scailbc** [lightning-js/solid#36]
How can you render a string that contains HTML?

In solidjs you can use the `innerHTML` property, do we have something similar in Lightning/Solid?

```js
function SolidComponent() {
  return <>
    <div>My div</div>
    <div innerHTML="<b>MY BOLD INNER</b>" />
  </>
}
```

**Comment by chiefcll** [comment]
This project is a webgl renderer - You don't use HTML at all.. You'd want to use <Text> and <View> component to render Text

**Comment by chiefcll** [comment]
I recommend checking out https://github.com/lightning-js/solid-demo-app

Eventually you'll be able to have HTML + Lightning as two apps in one project using Solid to write the code.
