### ISSUE TITLE
Removing src or color the border is not visible

### ISSUE THREAD

**Issue by pecoram** [lightning-js/solid#7]
A `<View />` without src or without the color style cause border not visible.

In this example:

https://github.com/lightning-js/solid-demo-app/blob/17c76185b05669863a22804befd9b57320fe0e5c/src/components/index.jsx#L7C1-L7C1

by setting
`<View {...props} src="" animate style={styles.Thumbnail} />`

and

```
Thumbnail: {
    borderRadius: 30,
    width: 185, height: 278, scale: 1, zIndex: 2,
    border: { width: 5, color: '#ffffff' },
    focus: { scale: 1.1, border: { width: 10, color: '#ffffff'}}
  },
```

I can't see the border.

To see it I have to set a color, and this color can't be with opacity 0 `color: '#00000000'`:

```
Thumbnail: {
    borderRadius: 30,
    width: 185, height: 278, scale: 1, zIndex: 2,
    color: '#000000'
    border: { width: 5, color: '#ffffff' },
    focus: { scale: 1.1, border: { width: 10, color: '#ffffff'}}
  },
```

**Comment by chiefcll** [comment]
Hi! Solid defaults color to transparent for nodes (unless it has a src image), which currently is affecting the borderShader. The renderer has a PR to address this which hopefully will be released this week. 

https://github.com/lightning-js/renderer/pull/18

**Comment by pecoram** [comment]
fixed
